export const CMS_REVALIDATE_INTERVAL = 86400 // 1 day

export const GITHUB_RELEASES_REVALIDATE_SECONDS = 86400 // 24h

export const GITHUB_RELEASES_STALE_WHILE_REVALIDATE_SECONDS = 3600 // 1h

export const GITHUB_RELEASES_EDGE_S_MAXAGE_SECONDS = 300 // 5 min

export const GITHUB_RELEASES_PARTIAL_S_MAXAGE_SECONDS = 120

export const GITHUB_RELEASES_PARTIAL_INSTANCE_MEMO_MS = 5 * 60 * 1000 // 5 min
