import type { ComponentItem } from './types'

const ICON_BASE_PATH = '/img/docs-listicles/icons'

const icon = (name: string) => `${ICON_BASE_PATH}/${name}.svg`

const ICON_BY_NAME: Record<string, string> = {
  aks: icon('azure'),
  'android-java': icon('android'),
  'android-kotlin': icon('android'),
  'apache-druid': icon('apache-druid'),
  'apache-web-server': icon('apache'),
  'api-gateway': icon('api'),
  apm: icon('activity'),
  'apm-metrics': icon('activity'),
  'argo-cd': icon('argocd'),
  argocd: icon('argocd'),
  'asp-net-core': icon('dotnet'),
  aws: icon('aws'),
  'aws-ec2': icon('aws-ec2'),
  'aws-ecs': icon('aws-ecs'),
  'aws-ecs-fargate': icon('aws-ecs'),
  'aws-eks': icon('aws-eks'),
  'aws-elasticache-redis': icon('redis'),
  'aws-rds': icon('database'),
  'aws-rds-mysql': icon('mysql'),
  'aws-rds-postgresql': icon('postgresql'),
  'aws-sqs-prometheus': icon('message-queue'),
  'azure-container-apps': icon('azure'),
  'azure-functions': icon('azure-functions'),
  'azure-openai-api': icon('azure-openai'),
  'azure-sql-database': icon('database'),
  'azure-vm': icon('server'),
  binary: icon('linux'),
  'blob-storage': icon('storage'),
  'bunyan-node-js': icon('nodejs'),
  c: icon('cpp'),
  'c-1': icon('cpp'),
  'cdn-frontdoor': icon('azure'),
  'cert-manager': icon('shield'),
  'ci-cd': icon('cicd'),
  'cloud-functions': icon('cloud'),
  'cloud-run': icon('cloud'),
  cloudflare: icon('cloudflare'),
  cloudwatch: icon('cloudwatch'),
  'codex-openai': icon('openai'),
  collection: icon('opentelemetry'),
  'container-apps': icon('container'),
  coolify: icon('coolify'),
  'database-calls-monitoring': icon('database'),
  'datadog-receiver': icon('datadog'),
  digitalocean: icon('digitalocean'),
  'digitalocean-marketplace': icon('digitalocean'),
  docker: icon('docker'),
  'docker-container-metrics': icon('docker'),
  'docker-swarm': icon('docker'),
  dynamodb: icon('dynamodb'),
  ec2: icon('aws-ec2'),
  ecs: icon('aws-ecs'),
  'ecs-ec2-daemon-service': icon('aws-ecs'),
  'ecs-infra-metrics': icon('container'),
  'ecs-serverless-sidecar': icon('aws-ecs'),
  eks: icon('aws-eks'),
  elasticache: icon('redis'),
  fluentbit: icon('fluentbit'),
  fluentd: icon('fluentd'),
  gcp: icon('gcp'),
  'gcp-cloud-monitoring': icon('gcp'),
  'gcp-compute-engine': icon('gcp'),
  'gcp-vpc': icon('gcp'),
  'github-actions-traces': icon('github'),
  'github-metrics': icon('github'),
  'gitlab-pipeline-traces': icon('gitlab'),
  go: icon('go'),
  golang: icon('go'),
  'golang-go': icon('go'),
  http: icon('http'),
  'http-api-monitoring': icon('api'),
  'http-endpoints': icon('http'),
  'http-logs': icon('http'),
  'hypercorn-unicorn': icon('python'),
  'ios-swiftui': icon('swift'),
  'java-spring-boot': icon('java'),
  'jenkins-agent-monitoring': icon('jenkins'),
  'jenkins-tracing': icon('jenkins'),
  jmx: icon('java'),
  'jvm-metrics': icon('java'),
  'k8s-infra-helm-chart': icon('kubernetes'),
  'k8s-serverless-eks-fargate': icon('kubernetes'),
  keda: icon('zap'),
  'kong-open-telemetry-plugin': icon('kong'),
  'kong-signoz-plugin': icon('kong'),
  kubernetes: icon('kubernetes'),
  lambda: icon('aws-lambda'),
  'lambda-node-js': icon('aws-lambda'),
  linux: icon('linux'),
  'log-files': icon('file'),
  logstash: icon('logstash'),
  'manual-js': icon('javascript'),
  'mongodb-atlas': icon('mongodb'),
  msk: icon('message-queue'),
  'nginx-ingress-controller': icon('nginx'),
  'node-js': icon('nodejs'),
  'open-telemetry-binary': icon('opentelemetry'),
  'opentelemetry-binary': icon('opentelemetry'),
  'opentelemetry-operator': icon('opentelemetry'),
  'otel-receivers': icon('opentelemetry'),
  'other-platform': icon('helm'),
  'pino-node-js': icon('nodejs'),
  prometheus: icon('prometheus'),
  rds: icon('database'),
  reactjs: icon('react'),
  'react-native': icon('react'),
  s3: icon('storage'),
  'self-hosted-signoz': icon('signoz'),
  'sending-web-vitals-as-metrics': icon('chart'),
  'sending-web-vitals-as-traces': icon('timeline'),
  standalone: icon('docker'),
  statsd: icon('chart'),
  swarm: icon('docker'),
  syslogs: icon('logs'),
  vector: icon('vector'),
  'virtual-machines': icon('server'),
  vm: icon('server'),
  'windows-event': icon('windows'),
  'winston-node-js': icon('nodejs'),
}

const ICON_BY_HREF_TOKEN: Array<[string, string]> = [
  ['amazon-bedrock', 'aws'],
  ['anthropic', 'anthropic'],
  ['apache-druid', 'apache-druid'],
  ['apache-web-server', 'apache'],
  ['api-gateway', 'api'],
  ['argocd', 'argocd'],
  ['aspnet', 'dotnet'],
  ['autogen', 'autogen'],
  ['aws', 'aws'],
  ['azure', 'azure'],
  ['baseten', 'baseten'],
  ['celery', 'celery'],
  ['cert-manager', 'shield'],
  ['cicd', 'cicd'],
  ['clickhouse', 'clickhouse'],
  ['claude', 'claude'],
  ['cloudflare', 'cloudflare'],
  ['cloudwatch', 'cloudwatch'],
  ['codex', 'openai'],
  ['confluent-kafka', 'kafka'],
  ['convex', 'convex'],
  ['coolify', 'coolify'],
  ['couchdb', 'database'],
  ['crewai', 'crewai'],
  ['datadog', 'datadog'],
  ['deepseek', 'deepseek'],
  ['deno', 'deno'],
  ['dify', 'dify'],
  ['digital-ocean', 'digitalocean'],
  ['docker', 'docker'],
  ['dynamodb', 'dynamodb'],
  ['ec2', 'aws-ec2'],
  ['ecs', 'aws-ecs'],
  ['eks', 'aws-eks'],
  ['elasticache', 'redis'],
  ['elixir', 'elixir'],
  ['envoy', 'envoy'],
  ['falcon', 'falcon'],
  ['fastapi', 'fastapi'],
  ['flask', 'flask'],
  ['fluentbit', 'fluentbit'],
  ['fluentd', 'fluentd'],
  ['fly', 'flyio'],
  ['frontend-monitoring', 'frontend'],
  ['gcp', 'gcp'],
  ['github', 'github'],
  ['gitlab', 'gitlab'],
  ['golang', 'go'],
  ['google-adk', 'google-adk'],
  ['google-gemini', 'gemini'],
  ['graphql', 'graphql'],
  ['grok', 'grok'],
  ['groq', 'groq'],
  ['haproxy', 'shield'],
  ['hasura', 'hasura'],
  ['haystack', 'haystack'],
  ['heroku', 'heroku'],
  ['hostmetrics', 'server'],
  ['huggingface', 'huggingface'],
  ['inkeep', 'inkeep'],
  ['istio', 'istio'],
  ['java', 'java'],
  ['jenkins', 'jenkins'],
  ['jmx', 'java'],
  ['jvm', 'java'],
  ['kafka', 'kafka'],
  ['keda', 'zap'],
  ['kong', 'kong'],
  ['kubernetes', 'kubernetes'],
  ['lambda', 'aws-lambda'],
  ['langchain', 'langchain'],
  ['langtrace', 'langtrace'],
  ['laravel', 'laravel'],
  ['linux', 'linux'],
  ['litellm', 'litellm'],
  ['livekit', 'livekit'],
  ['llamaindex', 'llamaindex'],
  ['logstash', 'logstash'],
  ['mastra', 'mastra'],
  ['memcached', 'storage'],
  ['microsoft-sql', 'sql-server'],
  ['mistral', 'mistral'],
  ['mongodb', 'mongodb'],
  ['mysql', 'mysql'],
  ['n8n', 'n8n'],
  ['neondb', 'neon'],
  ['newrelic', 'newrelic'],
  ['nginx', 'nginx'],
  ['nodejs', 'nodejs'],
  ['nomad', 'nomad'],
  ['nuxt', 'nuxt'],
  ['ollama', 'ollama'],
  ['openai', 'openai'],
  ['openclaw', 'openclaw'],
  ['opencode', 'opencode'],
  ['opentelemetry', 'opentelemetry'],
  ['openrouter', 'openrouter'],
  ['php', 'php'],
  ['pipecat', 'pipecat'],
  ['postgres', 'postgresql'],
  ['prometheus', 'prometheus'],
  ['pydantic', 'pydantic'],
  ['python', 'python'],
  ['qwen', 'qwen'],
  ['quarkus', 'quarkus'],
  ['rabbitmq', 'rabbitmq'],
  ['railway', 'railway'],
  ['react', 'react'],
  ['redis', 'redis'],
  ['render', 'render'],
  ['rust', 'rust'],
  ['s3', 'storage'],
  ['scala', 'scala'],
  ['semantic-kernel', 'semantic-kernel'],
  ['signoz', 'signoz'],
  ['slurm', 'server'],
  ['snowflake', 'snowflake'],
  ['spring', 'spring-boot'],
  ['sql-server', 'sql-server'],
  ['sqs', 'message-queue'],
  ['strimzi', 'kafka'],
  ['supabase', 'supabase'],
  ['swift', 'swift'],
  ['temporal', 'temporal'],
  ['tomcat', 'tomcat'],
  ['traefik', 'traefik'],
  ['traceloop', 'traceloop'],
  ['typescript', 'typescript'],
  ['vercel', 'vercel'],
  ['vpc', 'network'],
  ['vultr', 'vultr'],
  ['web-vitals', 'chart'],
  ['windows', 'windows'],
  ['wordpress', 'wordpress'],
]

const normalizeKey = (value: string) =>
  value
    .toLowerCase()
    .replace(/&/g, 'and')
    .replace(/\+/g, 'plus')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')

const iconFromHref = (href: string) => {
  const normalizedHref = href.toLowerCase()
  const match = ICON_BY_HREF_TOKEN.find(([token]) => normalizedHref.includes(token))
  return match ? icon(match[1]) : undefined
}

export function getComponentItemIcon(item: Pick<ComponentItem, 'name' | 'href'>): string {
  return ICON_BY_NAME[normalizeKey(item.name)] || iconFromHref(item.href) || icon('docs')
}

export function withComponentIcons<T extends Pick<ComponentItem, 'name' | 'href'>>(
  items: readonly T[],
  overrides: Record<string, string> = {}
): Array<T & { icon: string }> {
  return items.map((item) => ({
    ...item,
    icon: overrides[item.name] || overrides[item.href] || getComponentItemIcon(item),
  }))
}
