export const HOMEPAGE_BUTTON_CLASSES = {
  root: [
    'homepage-button',
    '[body.homepage-redesign-active_&]:flex',
    '[body.homepage-redesign-active_&]:h-8',
    '[body.homepage-redesign-active_&]:gap-0',
    '[body.homepage-redesign-active_&]:overflow-hidden',
    '[body.homepage-redesign-active_&]:rounded',
    '[body.homepage-redesign-active_&]:p-0',
    '[body.homepage-redesign-active_&]:transition-colors',
    '[body.homepage-redesign-active_&]:duration-200',
  ].join(' '),
  primary: [
    'homepage-button--primary',
    '[body.homepage-redesign-active_&]:bg-signoz_robin-500',
    '[body.homepage-redesign-active_&]:hover:bg-signoz_robin-400',
    '[body.homepage-redesign-active_&]:active:bg-signoz_robin-600',
  ].join(' '),
  secondary: [
    'homepage-button--secondary',
    '[body.homepage-redesign-active_&]:hover:bg-signoz_ink-300',
  ].join(' '),
  label: [
    'homepage-button__label',
    'flex',
    'min-w-0',
    'items-center',
    'justify-center',
    'gap-1.5',
    '[body.homepage-redesign-active_&]:h-full',
    '[body.homepage-redesign-active_&]:flex-1',
    '[body.homepage-redesign-active_&]:whitespace-nowrap',
    '[body.homepage-redesign-active_&]:px-3',
  ].join(' '),
  primaryLabel: '[body.homepage-redesign-active_&]:[&_svg:not(.animate-spin)]:hidden',
  icon: [
    'homepage-button__icon',
    'hidden',
    '[body.homepage-redesign-active_&]:h-full',
    '[body.homepage-redesign-active_&]:w-8',
    '[body.homepage-redesign-active_&]:shrink-0',
    '[body.homepage-redesign-active_&]:items-center',
    '[body.homepage-redesign-active_&]:justify-center',
    '[body.homepage-redesign-active_&]:rounded',
    '[body.homepage-redesign-active_&]:text-white',
  ].join(' '),
  primaryIcon: [
    '[body.homepage-redesign-active_&]:flex',
    '[body.homepage-redesign-active_&]:bg-signoz_robin-400',
  ].join(' '),
  secondaryIcon: '[body.homepage-redesign-active_&]:flex',
}
