// lib/content-pipeline/types-generator.ts
import type { Collection, CollectionsMap } from './define'
import { z, ZodType, ZodOptional, ZodDefault, ZodArray } from 'zod'

function zodToTsType(schema: ZodType): string {
  if (schema instanceof ZodOptional) {
    return zodToTsType(schema.unwrap())
  }
  if (schema instanceof ZodDefault) {
    return zodToTsType(schema._def.innerType)
  }
  if (schema instanceof ZodArray) {
    return `${zodToTsType(schema.element)}[]`
  }

  const typeName = schema._def.typeName

  switch (typeName) {
    case 'ZodString':
      return 'string'
    case 'ZodNumber':
      return 'number'
    case 'ZodBoolean':
      return 'boolean'
    case 'ZodDate':
      return 'Date'
    case 'ZodObject':
      return 'object'
    case 'ZodAny':
      return 'any'
    default:
      return 'unknown'
  }
}

function isOptional(schema: ZodType): boolean {
  return schema instanceof ZodOptional
}

function generateInterfaceFields(collection: Collection): string {
  const shape = collection.schema.shape
  const lines: string[] = []

  for (const [key, schema] of Object.entries(shape)) {
    const optional = isOptional(schema as ZodType) ? '?' : ''
    const tsType = zodToTsType(schema as ZodType)
    lines.push(`  ${key}${optional}: ${tsType}`)
  }

  return lines.join('\n')
}

function inferComputedFieldTypes(collection: Collection): string {
  // Call computedFields with a dummy doc to infer types
  const dummyDoc = {
    _file: { path: '', directory: '', name: '' },
    body: { raw: '', code: '' },
  }
  const dummyHelpers = {
    readingTime: () => ({ minutes: 0, words: 0, text: '' }),
    extractToc: () => [],
  }

  try {
    const computed = collection.computedFields(dummyDoc as any, dummyHelpers)
    const lines: string[] = []

    for (const [key, value] of Object.entries(computed)) {
      const tsType = inferValueType(value)
      lines.push(`  ${key}: ${tsType}`)
    }

    return lines.join('\n')
  } catch {
    return ''
  }
}

function inferValueType(value: unknown): string {
  if (value === null) return 'null'
  if (value === undefined) return 'undefined'
  if (typeof value === 'string') return 'string'
  if (typeof value === 'number') return 'number'
  if (typeof value === 'boolean') return 'boolean'
  if (Array.isArray(value)) {
    if (value.length === 0) return 'unknown[]'
    return `${inferValueType(value[0])}[]`
  }
  if (typeof value === 'object') {
    const entries = Object.entries(value)
    if (entries.length === 0) return 'object'
    const fields = entries.map(([k, v]) => `${k}: ${inferValueType(v)}`).join('; ')
    return `{ ${fields} }`
  }
  return 'unknown'
}

export function generateTypes(collections: CollectionsMap): string {
  const interfaces: string[] = []
  const names: string[] = []

  for (const [name, collection] of Object.entries(collections)) {
    names.push(name)

    const fields = generateInterfaceFields(collection)
    const computed = inferComputedFieldTypes(collection)

    interfaces.push(`
export interface ${name} {
${fields}
${computed}
  body: {
    raw: string
    code: string
  }
  _file: {
    path: string
    directory: string
    name: string
  }
}

export type ${name}Meta = Omit<${name}, 'body'>
`)
  }

  const header = `// Auto-generated by content-pipeline
// Do not edit manually
`

  const union = `export type DocumentTypes = ${names.join(' | ')}`

  return [header, ...interfaces, union].join('\n')
}
