import type {
  Collection,
  CollectionsMap,
  FieldDef,
  FieldsShape,
  FieldDefOrShorthand,
} from './define'
import { normalizeField } from './define'

function fieldToTsType(field: FieldDefOrShorthand): string {
  const f = normalizeField(field)

  let baseType: string
  switch (f.type) {
    case 'string':
      baseType = 'string'
      break
    case 'number':
      baseType = 'number'
      break
    case 'boolean':
      baseType = 'boolean'
      break
    case 'date':
      baseType = 'Date'
      break
    case 'any':
      baseType = 'any'
      break
    case 'array':
      if (f.of) {
        if (typeof f.of === 'string') {
          baseType = `${fieldToTsType({ type: f.of, required: true })}[]`
        } else {
          baseType = `${fieldToTsType(f.of)}[]`
        }
      } else {
        baseType = 'unknown[]'
      }
      break
    case 'object':
      if (f.shape) {
        baseType = generateInlineObject(f.shape)
      } else {
        baseType = 'Record<string, unknown>'
      }
      break
    default:
      baseType = 'unknown'
  }

  if (f.nullable) {
    baseType = `${baseType} | null`
  }

  return baseType
}

function generateInlineObject(shape: FieldsShape): string {
  const fields = Object.entries(shape)
    .map(([key, field]) => {
      const f = normalizeField(field)
      const optional = f.required === false ? '?' : ''
      return `${key}${optional}: ${fieldToTsType(field)}`
    })
    .join('; ')
  return `{ ${fields} }`
}

function generateFieldsFromShape(shape: FieldsShape): string {
  const lines: string[] = []

  for (const [key, field] of Object.entries(shape)) {
    const f = normalizeField(field)
    const optional = f.required === false ? '?' : ''
    const tsType = fieldToTsType(field)
    lines.push(`  ${key}${optional}: ${tsType}`)
  }

  return lines.join('\n')
}

export function generateTypes(collections: CollectionsMap): string {
  const interfaces: string[] = []
  const names: string[] = []

  for (const [name, collection] of Object.entries(collections)) {
    names.push(name)

    const schemaFields = generateFieldsFromShape(collection.fields)
    const computedFields = generateFieldsFromShape(collection.computedFields)

    interfaces.push(`
export interface ${name} {
${schemaFields}
${computedFields}
  body: {
    raw: string
    code: string
  }
  _file: {
    path: string
    directory: string
    name: string
  }
}

export type ${name}Meta = Omit<${name}, 'body'>
`)
  }

  const header = `// Auto-generated by content-pipeline
// Do not edit manually
`

  const union = `export type DocumentTypes = ${names.join(' | ')}`

  return [header, ...interfaces, union].join('\n')
}
