import type { Collection, CollectionsMap } from './define'
import {
  ZodType,
  ZodOptional,
  ZodDefault,
  ZodArray,
  ZodString,
  ZodNumber,
  ZodBoolean,
  ZodDate,
  ZodObject,
  ZodAny,
  ZodNullable,
  ZodEnum,
  ZodUnion,
  ZodLiteral,
} from 'zod'

function zodToTsType(schema: ZodType): string {
  if (schema instanceof ZodOptional) {
    return zodToTsType(schema.unwrap())
  }
  if (schema instanceof ZodDefault) {
    return zodToTsType(schema._def.innerType)
  }
  if (schema instanceof ZodNullable) {
    return `${zodToTsType(schema.unwrap())} | null`
  }
  if (schema instanceof ZodArray) {
    return `${zodToTsType(schema.element)}[]`
  }
  if (schema instanceof ZodString) {
    return 'string'
  }
  if (schema instanceof ZodNumber) {
    return 'number'
  }
  if (schema instanceof ZodBoolean) {
    return 'boolean'
  }
  if (schema instanceof ZodDate) {
    return 'Date'
  }
  if (schema instanceof ZodLiteral) {
    const val = schema._def.value
    return typeof val === 'string' ? `'${val}'` : String(val)
  }
  if (schema instanceof ZodEnum) {
    return schema._def.values.map((v: string) => `'${v}'`).join(' | ')
  }
  if (schema instanceof ZodUnion) {
    return schema._def.options.map((o: ZodType) => zodToTsType(o)).join(' | ')
  }
  if (schema instanceof ZodObject) {
    const shape = schema.shape
    const fields = Object.entries(shape)
      .map(([key, val]) => {
        const optional = isOptional(val as ZodType) ? '?' : ''
        return `${key}${optional}: ${zodToTsType(val as ZodType)}`
      })
      .join('; ')
    return `{ ${fields} }`
  }
  if (schema instanceof ZodAny) {
    return 'any'
  }
  return 'unknown'
}

function isOptional(schema: ZodType): boolean {
  return schema instanceof ZodOptional
}

function generateFieldsFromSchema(schema: ZodObject<any>): string {
  const shape = schema.shape
  const lines: string[] = []

  for (const [key, fieldSchema] of Object.entries(shape)) {
    const optional = isOptional(fieldSchema as ZodType) ? '?' : ''
    const tsType = zodToTsType(fieldSchema as ZodType)
    lines.push(`  ${key}${optional}: ${tsType}`)
  }

  return lines.join('\n')
}

export function generateTypes(collections: CollectionsMap): string {
  const interfaces: string[] = []
  const names: string[] = []

  for (const [name, collection] of Object.entries(collections)) {
    names.push(name)

    const schemaFields = generateFieldsFromSchema(collection.schema)
    const computedFields = generateFieldsFromSchema(collection.computedFieldsSchema)

    interfaces.push(`
export interface ${name} {
${schemaFields}
${computedFields}
  body: {
    raw: string
    code: string
  }
  _file: {
    path: string
    directory: string
    name: string
  }
}

export type ${name}Meta = Omit<${name}, 'body'>
`)
  }

  const header = `// Auto-generated by content-pipeline
// Do not edit manually
`

  const union = `export type DocumentTypes = ${names.join(' | ')}`

  return [header, ...interfaces, union].join('\n')
}
